config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'users/new'
  get  '/signup' , to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create' 
  post 'questions',to: 'questions#create'
  get '/search',  to: 'questions#new' 
  post '/search',  to: 'questions#search'
  get '/logout', to: 'sessions#destroy'
  post '/post_answer', to: 'answers#create'
  post '/post_comment', to: 'comments#create'
  post '/post_vote', to: 'votes#create'
  get '/show_question', to: 'questions#index'
  get '/show_user', to: 'users#index'
  get '/show_answer', to: 'answers#index'
  get '/delete_question', to: 'questions#destroy'
  get '/delete_answer', to: 'answers#destroy'
  post '/post_tags', to: 'tags#create'
  get '/show_comment', to: 'comments#index'
  get 'delete_comment', to: 'comments#destroy'
  # get '/questions', to: 'questions#show'
  # patch 'questions/:id', to: 'questions#update'
  post '/edit_question', to: 'questions#update'
  get '/edit_question', to: 'questions#edit'

  post '/edit_answer', to: 'answers#update'
  get '/edit_answer', to: 'answers#edit'

  post '/edit_comment', to: 'comments#update'
  get '/edit_comment', to: 'comments#edit'


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		if session[:user_id]
			uri = URI('http://localhost:3000/questions')
			question_params = {question_id: params["id"], user_id: session[:user_id]  }
			uri.query = URI.encode_www_form(question_params)
			@question_res = Net::HTTP.get_response(uri)

			if @question_res.code == "200"
				@question_res = JSON.parse(@question_res.body)
				render 'questions/question'
			else
				@error_message = "Record does not exist !! "
				render 'errors/error'
			end
		else
			flash[:notice] = "Please login to view this page"
			redirect_to controller: 'sessions', action: 'new'
		end
	end

	def new
		uri = URI('http://localhost:3000/tags')
		tag_params = {tag: '' }
		uri.query = URI.encode_www_form(tag_params)
		tag_res = Net::HTTP.get_response(uri)
		@tag = tag_res.body
		@tag = JSON.parse(@tag)
	end

	def create
		if params["question"].empty?
			flash[:alert] ="Please enter valid Question !! "
			redirect_to controller: 'users', action: 'index'
		else
			uri = URI('http://localhost:3000/questions')
			tag_params = {question: params[:question], "tags[]": params[:tags].split(","), user_id: session[:user_id]  }
			res = Net::HTTP.post_form(uri, tag_params)
			@posted_question = JSON.parse(res.body)
			redirect_to controller: 'questions', action: 'index', id: @posted_question["id"]
			# render 'users/show'
		end
	end

	def search

		if params[:tags] != ""
			uri = URI('http://localhost:3000/search')
			tag_list = params[:tags].split(",")
			res = Net::HTTP.post_form(uri, "tags[]" => tag_list)
			@search_data = res.body
			@search_data = JSON.parse(@search_data)
			@search_data = @search_data.paginate(:page => 1, :per_page => 10)
			render 'show'
		else
			flash[:alert] = "Please Enter Tags"
			redirect_to controller: 'questions', action: 'new'
		end
	end

	def destroy
		uri = URI('http://localhost:3000/questions/1')
		http = Net::HTTP.new(uri.host, uri.port)
		attribute_url = '?'
		body = { user_id: session["user_id"] , question_id: params[:id] }
		attribute_url << body.map{|k,v| "#{k}=#{v}"}.join('&')
    request = Net::HTTP::Delete.new(uri.request_uri + attribute_url)
		response = http.request(request)
		
		redirect_to controller: 'users', action: 'index'
	end


	def edit
		if session[:user_id]
			uri = URI('http://localhost:3000/questions')
			question_params = {question_id: params["id"], user_id: session[:user_id]  }
			uri.query = URI.encode_www_form(question_params)
			@question_res = Net::HTTP.get_response(uri)

			if @question_res.code == "200"
				@question_res = JSON.parse(@question_res.body)
			else
				@error_message = "Record does not exist !! "
			end
		else
			flash[:notice] = "Please login to view this page"
			redirect_to controller: 'sessions', action: 'new'
		end		
	end
	
	def update
		if session[:user_id]
			uri = URI('http://localhost:3000/questions/1')
			req = Net::HTTP::Put.new(uri)
			req.set_form_data('user_id' => session[:user_id], 'question_id' => params[:id], "question": params[:value] )
			res = Net::HTTP.start(uri.hostname, uri.port) do |http|
				http.request(req)
			end

			if res.code == "200"
				res = JSON.parse(res.body)
				redirect_to controller: 'questions', action: 'index', id: res["id"]
			else
				@error_message = "Record does not exist !! "
				render 'errors/error'
			end
		else
			flash[:notice] = "Please login to view this page"
			redirect_to controller: 'sessions', action: 'new'
		end
	end

end

app/views/questions/edit.html.erb
<% provide(:title, "Edit Question") %>

<div class="row">
	<%= form_with(url: edit_question_path) do |f| %>
		<div class="col-sm-1">
			<label>Question:</label><br>
		</div>

		<div class="col-sm-10">
			<%= f.hidden_field :id, value: @question_res["id"]  %>
			<%= f.text_field :value, value: @question_res["value"]  %><br>
		</div>

		<div class="col-sm-1">
			<%= f.submit "Post", class: "btn btn-primary" %>
		</div>
	<% end %>
</div>

app/views/questions/new.html.erb
<% provide(:title, "Search") %>
<center> <h3> Search </h3> </center>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: search_path) do |f| %>

      <%= f.text_field :tags, class: 'form-control', placeholder: "Please Enter Comma(,) Separated Tags " %>
      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

<hr>

<center> <h3> Available Tags </h3> </center>

<% (0..@tag.length-1).step(4).each do |index| %>
  <div class="row">
    
  <div class="col-sm-3">
    <p> <%= @tag[index]["value"] if @tag[index] %> </p>
  </div>

  <div class="col-sm-3">
    <p> <%= @tag[index+1]["value"] if @tag[index+1] %> </p>
  </div>

  <div class="col-sm-3">
    <p> <%= @tag[index+2]["value"] if @tag[index+2] %> </p>
  </div>

  <div class="col-sm-3">
    <p> <%= @tag[index+3]["value"] if @tag[index+3] %> </p>
  </div>

  </div>
<% end %>  

app/views/questions/question.html.erb
<% provide(:title, "Question") %>
<% if @question_res %>

	<div class="row">
		<div class="col-sm-12">
		 	<strong> <%= @question_res["user"]["name"] %> </strong> Posted Below Question -  
		</div>
	</div>
	<br>

	<div class="row">
		<div class="col-sm-1">
			<h4> Question:</h4>
		</div>
		<div class="col-sm-11" >
			<h4> <%= @question_res["value"] %> </h4>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-1">
			<h5> Tags: </h5>
		</div>

		<div class="col-sm-11">
			<% tag_list = @question_res["tags"].map { |tag| tag["value"] } %>
			<% tags = tag_list.join(", ") %>
			<h5> <%= tags %> </h5>
		</div>
	</div>

	<hr>
	<div class="row">
		<div class="col-sm-3">
			<%= form_with(url: post_answer_path ) do |f| %>

				<%= f.text_field :answer, placeholder: "Write an answer" %>
				<%= f.hidden_field :id, value: @question_res["id"]  %>

				<%= f.submit "Post your Answer", class: "btn btn-primary" %>
			<% end %>
		</div>

		<div class="col-sm-3">
			<%= form_with(url: post_comment_path ) do |f| %>

				<%= f.text_field :comment, placeholder: "Post Your Comment" %>
				<%= f.hidden_field :id, value: @question_res["id"]  %>
				<%= f.hidden_field :type, value: "Question" %>
				<%= f.submit "Post your Comment", class: "btn btn-primary" %>
			<% end %>
		</div>

		<div class="col-sm-2">
			<%= form_with(url: post_vote_path ) do |f| %>
				
				<%= f.hidden_field :id, value: @question_res["id"]  %>
				<%= f.hidden_field :type, value: "Question" %>
				<%= f.select :weight, options_for_select([['UP', "upvote"], ['DOWN', "downvote"]]) %>
				<%= f.submit "Vote", class: "btn btn-primary" %>
			<% end %>
		</div>

		<% if session[:user_id] == @question_res["user"]["id"] %>
			<div class="col-sm-1">
				<%= form_with(url: edit_question_path, method: "get") do |f| %>
					<%= f.hidden_field :id, value: @question_res["id"]  %>
					<%= f.submit "Edit", class: "btn btn-primary" %>
				<% end %>
			</div>
		<% end %>
		
				
		<% if session[:user_id] == @question_res["user"]["id"] %>
			<div class="col-sm-3">
				<%= form_with(url: delete_question_path, method: "get") do |f| %>
					<%= f.hidden_field :id, value: @question_res["id"]  %>
					<%= f.submit "Delete Question", class: "btn btn-primary" %>
				<% end %>
			</div>
		<% end %>

	</div>
	<hr>

	<div class="row">
		<div class="col-sm-2">
		</div>	
	 
		<div class="col-sm-2">
			<strong> UPVOTES: </strong>
		</div>

		<div class="col-sm-2">
		  <h1> <%= @question_res["votes"]["upvote"] %> </h1>
		</div>

		<div class="col-sm-2">
		  <strong> DOWNVOTES: </strong>
		</div>
		
		<div class="col-sm-2">
			<h1> <%= @question_res["votes"]["downvote"] %> </h1>
		</div>

		<div class="col-sm-2">
		</div>
	</div>
	<hr>
	<center> <h3> Answers </h3> </center><br>
	<% ans_count=1 %>
	<% @question_res["answers"].each do |answer| %>
		<% if answer["value"] %>
			<div class="row">
				<div class="col-sm-5">
					<p> <%= ans_count %>. &nbsp; <%= answer["value"] %> </p>
				</div>
				
				<div class="col-sm-2">		
					<%= form_with(url: post_comment_path ) do |f| %>
						<%= render 'shared/error_messages' %>
						<%= f.hidden_field :id, value: answer["id"] %>
						<%= f.text_field :comment, placeholder: "Write a comment" %>
						<%= f.hidden_field :type, value: "Answer" %>
				</div>
				
				<div class="col-sm-2">
					<%= f.submit "Post your commemt", class: "btn btn-primary" %>
				</div>
					<% end %>

				<div class="col-sm-1">
					<%= form_with(url: post_vote_path ) do |f| %>
						<%= render 'shared/error_messages' %>
						
						<%= f.hidden_field :id, value: answer["id"]  %>
						<%= f.hidden_field :type, value: "Answer" %>
						<%= f.select :weight, options_for_select([['UP', "upvote"], ['DOWN', "downvote"]]) %>
				</div>
				
				<div class="col-sm-1">
						<%= f.submit "Vote", class: "btn btn-primary" %>
				</div>
					<% end %>
				
				<div class="col-sm-1">
					<%= form_with(url: show_answer_path, method: "get" ) do |f| %>
						<%= f.hidden_field :id, value: answer["id"]  %>
						<%= f.submit "Show", class: "btn btn-primary" %>
					<% end %>
				</div>
			</div>
			<% ans_count += 1 %>
		<% end %>
	<% end %>
	<hr>

	<center> <h3> Comments </h3> </center><br>
	<% comment_count = 1 %>
	<% @question_res["comments"].each do |comment| %>		
		<% if comment["value"] %>
			<div class="row">
				<div class="col-sm-10">
					<p> <%= comment_count %>. <%= comment["value"] %>
				</div>
				
				<div class="col-sm-2">
					<%= form_with(url: show_comment_path, method: "get") do |f| %>
						<%= f.hidden_field :id, value: comment["id"]  %>
						<%= f.hidden_field :type, value: "Question"  %>
						<%= f.hidden_field :type_id, value: @question_res["id"]  %>
						<%= f.submit "Show", class: "btn btn-primary" %>
					<% end %>
				</div> 
			</div>
			<% comment_count += 1 %>
		<% end %>
	<% end %>

<% end %>

app/views/questions/show.html.erb
<% provide(:title, "Search Result" ) %>
<!--  <div class="row">
  <aside class="col-md-12">
    <section class="search_info">
      <h1>
        <%= @search_data %>
      </h1>
    </section>
  </aside>
</div> -->


<% if @search_data %>
	<h4> Question </h4>
	<% count = 1 %>
	<% @search_data.each do |question| %>
		<% if question["value"] %>
			<div class="row">
				<div class="col-sm-5">
					<strong> Question - <%= count %>  </strong> <%= question["value"] %> 
				</div>

				<% if logged_in? %>
					<div class="col-sm-2">
						<%= form_with(url: post_answer_path ) do |f| %>
							<%= render 'shared/error_messages' %>

							<%= f.text_field :answer, placeholder: "Write an answer" %>
							<%= f.hidden_field :id, value: question["id"]  %>
							<%= f.hidden_field :type, value: "Question" %>
					</div>
					<div class="col-sm-2">
						<%= f.submit "Post your Answer", class: "btn btn-primary" %>
					</div>
						<% end %>
					<div class="col-sm-1">
						<%= form_with(url: post_vote_path ) do |f| %>
							<%= render 'shared/error_messages' %>
							
							<%= f.hidden_field :id, value: question["id"]  %>
							<%= f.hidden_field :type, value: "Question" %>
							<%= f.select :weight, options_for_select([['UP', "upvote"], ['DOWN', "downvote"]]) %>
					</div>
					<div class="col-sm-1">
							<%= f.submit "Vote", class: "btn btn-primary" %>
					</div>
						<% end %>
					
					<div class="col-sm-1">
						<%= form_with(url: show_question_path, method: "get" ) do |f| %>
							<%= f.hidden_field :id, value: question["id"]  %>
							<%= f.submit "Show", class: "btn btn-primary" %>
						<% end %>
					</div>
			  <% end %>
				
			</div>
			
			<h4> Question Votes </h4>
			<div class="row">
				<div class="col-sm-3">
				</div>
				<div class="col-sm-3">
					<strong> Upvote : </strong> <%= question["votes"]["upvote"] %>
				</div>

				<div class="col-sm-3">
					<strong> Downvote : </strong> <%= question["votes"]["downvote"] %>
				</div>
				<div class="col-sm-3">
				</div>
			</div>

			<h4> Answer </h4> 
			<% ans_count = 1 %>
			<% question["answers"].each do |answers| %>
				<% if answers["value"] %>
					<div class="row">
						<div class="col-sm-5">
							<p> <%= ans_count %> <%= answers["value"] %> </p>
						</div>

						<% if logged_in? %>
							<div class="col-sm-2">		
								<%= form_with(url: post_comment_path ) do |f| %>
									<%= render 'shared/error_messages' %>
									
									<%= f.hidden_field :id, value: answers["id"] %>
									<%= f.hidden_field :type, value: "Answer" %>
									<%= f.text_field :comment, placeholder: "Write a comment" %>
							</div>
							<div class="col-sm-2">
								<%= f.submit "Post your commemt", class: "btn btn-primary" %>
							</div>
								<% end %>

							<div class="col-sm-1">
								<%= form_with(url: post_vote_path ) do |f| %>
									<%= render 'shared/error_messages' %>
									
									<%= f.hidden_field :id, value: answers["id"]  %>
									<%= f.hidden_field :type, value: "Answer" %>
									<%= f.select :weight, options_for_select([['UP', "upvote"], ['DOWN', "downvote"]]) %>
							</div>
							
							<div class="col-sm-1">
									<%= f.submit "Vote", class: "btn btn-primary" %>
							</div>
								<% end %>
							
							<div class="col-sm-1">
								<%= form_with(url: show_answer_path, method: "get" ) do |f| %>
									<%= f.hidden_field :id, value: answers["id"]  %>
									<%= f.submit "Show", class: "btn btn-primary" %>
								<% end %>
							</div>
						<% end %>
					
						</div>
					<% ans_count+= 1 %>
				<% end %>
			<% end %>

				<h4> Comments </h4>
				<% comment_count = 1 %>
				<% question["comments"].each do |comment| %>
					<% if comment["value"] %>
						<div class="row">
							<div class="col-sm-10">
								<strong> Comment - <%= comment_count %>  </strong> <%= comment["value"] %>
							</div>
							<% if logged_in? %>
								<div class="col-sm-2">
									<%= form_with(url: show_comment_path, method: "get") do |f| %>
										<%= f.hidden_field :id, value: comment["id"]  %>
										<%= f.hidden_field :type, value: "Question"  %>
										<%= f.hidden_field :type_id, value: question["id"]  %>
										<%= f.submit "Show", class: "btn btn-primary" %>
									<% end %>
								</div> 
							<% end %>
						</div>
						<br>
					<% comment_count += 1 %>
					<% end %>
				<% end %>
				
				<h4> User Information </h4>
				<div class="row">
					<div class="col-sm-4">
						<strong> Name : </strong> <%= question["user"]["name"] %>
					</div>

					<div class="col-sm-4">
						<strong> Email : </strong> <%= question["user"]["email"] %>
					</div>

					<div class="col-sm-4">
						<strong> Reputation : </strong> <%= question["user"]["reputation"] %>
					</div>

				</div>

			<hr>
			<% count += 1 %>
		<% end %>
	<% end %>
<% end %>

<% if @posted_vote %>
	<div class="row">
		<div class="col-sm-12">
			<strong> Message : </strong> <%= @posted_vote %>
		</div>
	</div>
<% end %>