config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'users/new'
  get  '/signup' , to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create' 
  post 'questions',to: 'questions#create'
  get '/search',  to: 'questions#new' 
  post '/search',  to: 'questions#search'
  get '/logout', to: 'sessions#destroy'
  post '/post_answer', to: 'answers#create'
  post '/post_comment', to: 'comments#create'
  post '/post_vote', to: 'votes#create'
  get '/show_question', to: 'questions#index'
  get '/show_user', to: 'users#index'
  get '/show_answer', to: 'answers#index'
  get '/delete_question', to: 'questions#destroy'
  get '/delete_answer', to: 'answers#destroy'
  post '/post_tags', to: 'tags#create'
  get '/show_comment', to: 'comments#index'
  get 'delete_comment', to: 'comments#destroy'
  # get '/questions', to: 'questions#show'
  # patch 'questions/:id', to: 'questions#update'
  post '/edit_question', to: 'questions#update'
  get '/edit_question', to: 'questions#edit'

  post '/edit_answer', to: 'answers#update'
  get '/edit_answer', to: 'answers#edit'

  post '/edit_comment', to: 'comments#update'
  get '/edit_comment', to: 'comments#edit'


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		if params["comment"].empty?
			flash[:alert] = "Please Enter Valid Comment"

		else
			uri = URI('http://localhost:3000/comments')
			comment_params = {user_id: session[:user_id], commentable_type: params[:type], commentable_id: params[:id], comment: params[:comment] }
			res = Net::HTTP.post_form(uri, comment_params)
			@posted_comment = JSON.parse(res.body)

			# render 'questions/show'
		end
		

		if params[:type] == "Question"
			redirect_to controller: 'questions', action: 'index', id: params["id"]
		else
			redirect_to controller: 'answers', action: 'index', id: params["id"]
		end

	end

	def index
		if session[:user_id]
			uri = URI('http://localhost:3000/comments')
			comment_params = {commentable_id: params["id"], user_id: session[:user_id]  }
			uri.query = URI.encode_www_form(comment_params)
			@comment_res = Net::HTTP.get_response(uri)

			if @comment_res.code == "200"
				@comment_res = JSON.parse(@comment_res.body)

				@comment_type = params[:type]
				@comment_type_id = params[:type_id]

				render 'comments/comment'
			else
				@error_message = "Record does not exist !! "
				render 'errors/error'
			end

		else
			flash[:notice] = "Please login to view this page"
			redirect_to controller: 'sessions', action: 'new'
		end
	end

	def destroy
		uri = URI('http://localhost:3000/comments/1')
		http = Net::HTTP.new(uri.host, uri.port)
		attribute_url = '?'
		body = { user_id: session["user_id"] , comment_id: params[:id] }
		attribute_url << body.map{|k,v| "#{k}=#{v}"}.join('&')
    request = Net::HTTP::Delete.new(uri.request_uri + attribute_url)
		response = http.request(request)
		flash[:notice] = response.body

		if params[:type] == "Question"	
			redirect_to controller: 'questions', action: 'index', id: params[:type_id] 
		else
			redirect_to controller: 'answers', action: 'index', id: params[:type_id]
		end
	end


	def edit
		if session[:user_id]
			uri = URI('http://localhost:3000/comments')
			comment_params = {user_id: session[:user_id], commentable_type: params[:type], commentable_id: params[:id], comment: params[:comment] }
			uri.query = URI.encode_www_form(comment_params)
			@comment_res = Net::HTTP.get_response(uri)

			if @comment_res.code == "200"
				@comment_res = JSON.parse(@comment_res.body)
				@comment_type = params[:type]
				@comment_type_id = params[:id]
			else
				@error_message = "Record does not exist !! "
			end
		else
			flash[:notice] = "Please login to view this page"
			redirect_to controller: 'sessions', action: 'new'
		end		
	end
	
	def update

		if session[:user_id]
			uri = URI('http://localhost:3000/comments/1')
			req = Net::HTTP::Put.new(uri)
			req.set_form_data('user_id' => session[:user_id], 'comment_id' => params[:id], "comment": params[:value] )
			res = Net::HTTP.start(uri.hostname, uri.port) do |http|
				http.request(req)
			end

			if res.code == "200"
				res = JSON.parse(res.body)
				
				if params[:type] == "Question"	
					redirect_to controller: 'questions', action: 'index', id: params[:type_id] 
				else
					redirect_to controller: 'answers', action: 'index', id: params[:type_id]
				end
				
			else
				@error_message = "Record does not exist !! "
				render 'errors/error'
			end
		else
			flash[:notice] = "Please login to view this page"
			redirect_to controller: 'sessions', action: 'new'
		end
	end

end

app/views/comments/comment.html.erb
<% provide(:title, "Comment" ) %>

<% if @comment_res %>

	<div class="row">
		<div class="col-sm-12">
			Below is a comment for <strong> <%= @comment_type %> </strong>
		</div>
	</div>


	<div class="row">

		<div class="col-sm-12">
			<strong> <%= @comment_res["user"]["name"] %> </strong> Posted Below Comment -  
		</div>

	</div>

	<hr>

	<div class="row">
		<div class="col-sm-2">
			<h4>Comment:</h4>
		</div>
		<div class="col-sm-8" >
			<h4> <%= @comment_res["value"] %> </h4>
		</div>

		<% if session[:user_id] == @comment_res["user"]["id"] %>
			<div class="col-sm-1" >
				<%= form_with(url: delete_comment_path, method: "get") do |f| %>
					<%= f.hidden_field :id, value: @comment_res["id"]  %>
					<%= f.hidden_field :type, value: @comment_type  %>
					<%= f.hidden_field :type_id, value: @comment_type_id  %>
					<%= f.submit "Delete", class: "btn btn-primary" %>
				<% end %>
			</div>

				<div class="col-sm-1">
					<%= form_with(url: edit_comment_path, method: "get") do |f| %>
						<%= f.hidden_field :id, value: @comment_res["id"]  %>
						<%= f.hidden_field :type, value: @comment_type  %>
						<%= f.hidden_field :type_id, value: @comment_type_id  %>
						<%= f.submit "Edit", class: "btn btn-primary" %>
					<% end %>
			</div>

		<% end %>

	</div>





<% end %>

app/views/comments/edit.html.erb
<% provide(:title, "Edit Comment") %>

<div class="row">
	<%= form_with(url: edit_comment_path) do |f| %>
		<div class="col-sm-1">
			<label>Comment:</label><br>
		</div>

		<div class="col-sm-10">
			<%= f.hidden_field :id, value: @comment_res["id"]  %>
			<%= f.hidden_field :type_id, value: @comment_type_id  %>
			<%= f.hidden_field :type, value: @comment_type  %>
			<%= f.text_field :value, value: @comment_res["value"]  %><br>
		</div>

		<div class="col-sm-1">
			<%= f.submit "Post", class: "btn btn-primary" %>
		</div>
	<% end %>
</div>