config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'users/new'
  get  '/signup' , to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create' 
  post 'questions',to: 'questions#create'
  get '/search',  to: 'questions#new' 
  post '/search',  to: 'questions#search'
  get '/logout', to: 'sessions#destroy'
  post '/post_answer', to: 'answers#create'
  post '/post_comment', to: 'comments#create'
  post '/post_vote', to: 'votes#create'
  get '/show_question', to: 'questions#index'
  get '/show_user', to: 'users#index'
  get '/show_answer', to: 'answers#index'
  get '/delete_question', to: 'questions#destroy'
  get '/delete_answer', to: 'answers#destroy'
  post '/post_tags', to: 'tags#create'
  get '/show_comment', to: 'comments#index'
  get 'delete_comment', to: 'comments#destroy'
  # get '/questions', to: 'questions#show'
  # patch 'questions/:id', to: 'questions#update'
  post '/edit_question', to: 'questions#update'
  get '/edit_question', to: 'questions#edit'

  post '/edit_answer', to: 'answers#update'
  get '/edit_answer', to: 'answers#edit'

  post '/edit_comment', to: 'comments#update'
  get '/edit_comment', to: 'comments#edit'


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user
	end

	def index

		if !(session["user_id"])
			user_params = { user_id: params["id"] }
		else
			user_params = {user_id: session["user_id"]}
		end

		uri = URI('http://localhost:3000/users')
		
		uri.query = URI.encode_www_form(user_params)
		@user = Net::HTTP.get_response(uri)

		if @user.code == "200"
			@user = @user.body
			@user = JSON.parse(@user)

			uri = URI('http://localhost:3000/tags')
			tag_params = {tag: '', user_id: @user["id"] }
			uri.query = URI.encode_www_form(tag_params)
			tag_res = Net::HTTP.get_response(uri)
			@tag = tag_res.body			
			@tag = JSON.parse(@tag)

			render 'users/show'
		else
			flash[:notice] = "Please login to Post an Answer !! "
			redirect_to controller: 'sessions', action: 'new'
		end
	end

	def create
		if params[:name].empty? || params[:email].empty? || params[:password].empty?
			flash[:alert] = "Please provide valid values"
			redirect_to controller: 'users', action: 'new'
		else
			uri = URI('http://localhost:3000/users')
			user_params = {name: params[:name], email: params[:email], password: params[:password]  }
			res = Net::HTTP.post_form(uri, user_params)

			if res.code == "200"
				@user = res.body
				@user = JSON.parse(@user)
				log_in @user
				redirect_to controller: 'users', action: 'index', id: @user["id"]
			else
				flash[:alert] = "Email already Exists"
				redirect_to controller: 'users', action: 'new'
			end
			
		end
		# render 'static_pages/home'
  end

end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
	def gravatar_for(user, options =  { size: 0 } )
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/users/new.html.erb
<% provide(:title, "Sign-up") %>

<h1>Sign up</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">
	<%= form_with(url: signup_path ) do |f| %>
		<%= render 'shared/error_messages' %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.email_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit "Create my account", class: "btn btn-primary" %>
	<% end %>
</div>
</div>

app/views/users/show.html.erb
<% if @user %>
<% provide(:title, "User Info" ) %>
<center> <h3> User Information </h3> </center> <br>
<div class="row">
	<div class="col-sm-4">
		Name : <strong> <%= @user["name"] %> </strong>
	</div>

	<div class="col-sm-4">
		Email : <strong> <%= @user["email"] %> </strong>
	</div>

	<div class="col-sm-4">
		Reputation : <strong> <%= @user["reputation"] %> </strong>
	</div>

</div>
<hr>      
<center> <h3> Posted Questions </h3> </center>
	<% count = 1 %>
	<% @user["questions"].each do |question| %>
		<% if question["value"] %>
			<div class="row">
				<div class="col-sm-7">
					
						<strong> Question- <%= count %>. </strong> <%= question["value"] %><br> 
						<% count += 1 %>
				</div>

				<div class="col-sm-2">
					<%= form_with(url: delete_question_path, method: "get") do |f| %>
						<%= f.hidden_field :id, value: question["id"]  %>
						<%= f.submit "Delete", class: "btn btn-primary" %>
					<% end %>
				</div>

				<div class="col-sm-2">
					<%= form_with(url: show_question_path, method: "get") do |f| %>
						<%= f.hidden_field :id, value: question["id"]  %>
						<%= f.submit "Show", class: "btn btn-primary" %>
					<% end %>
				</div>
				
				<div class="col-sm-1">
					<%= form_with(url: edit_question_path, method: "get") do |f| %>
						<%= f.hidden_field :id, value: question["id"]  %>
						<%= f.submit "Edit", class: "btn btn-primary" %>
					<% end %>
				</div>

			</div>	
			<br>
		<% end %>
	<% end %>
	<hr>
<center>	<h3> Posted Answers </h3> </center>
	<% count = 1 %>
	<% @user["answers"].each do |answer| %>
		<% if answer["value"] %>
			<div class="row">
				<div class="col-sm-7">
						<strong> Answer - <%= count %>. </strong> <%= answer["value"] %>
						<% count += 1 %>
				</div>

				<div class="col-sm-2">
					<%= form_with(url: delete_answer_path, method: "get") do |f| %>
						<%= f.hidden_field :id, value: answer["id"]  %>
						<%= f.submit "Delete", class: "btn btn-primary" %>
					<% end %>
				</div>

				<div class="col-sm-2">
					<%= form_with(url: show_answer_path, method: "get") do |f| %>
						<%= f.hidden_field :id, value: answer["id"]  %>
						<%= f.submit "Show", class: "btn btn-primary" %>
					<% end %>
				</div>

				<div class="col-sm-1">
					<%= form_with(url: edit_answer_path, method: "get") do |f| %>
						<%= f.hidden_field :id, value: answer["id"]  %>
						<%= f.submit "Edit", class: "btn btn-primary" %>
					<% end %>
				</div>

			</div>
			<br>
		<% end %>	
	<% end %>
	
<% end %>
<hr>

<center> <h3> Post Your Question </h3> </center> <br>
<%= form_with(url: questions_path ) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="row">
		<div class="col-sm-5">
			<%= f.text_field :question, placeholder: "Please Enter Questions" %>
		</div>

		<div class="col-sm-5">
			<%= f.text_field :tags, placeholder: "Please Enter Tags" %>
		</div>

		<div class="col-sm-2">
			<%= f.submit "POST", class: "btn btn-primary" %>
		</div>
</div>
<% end %>

<% if is_admin? %>
<hr>
	<center> <h3> Post Your Tags </h3> </center> <br>
	<%= form_with(url: post_tags_path ) do |f| %>
		<%= render 'shared/error_messages' %>
		<div class="row">
			<div class="col-sm-10">
				<%= f.text_field :tags, placeholder: "Please Enter comma(,) separated Tags" %>
			</div>

			<div class="col-sm-2">
				<%= f.submit "POST", class: "btn btn-primary" %>
			</div>
	</div>
	<% end %>
<% end %>



<hr>
<% if @tag %>
	<center> <h3> Available Tags </h3> </center>

	<% (0..@tag.length-1).step(4).each do |index| %>
		<div class="row">
			
		<div class="col-sm-3">
			<p> <%= @tag[index]["value"] if @tag[index] %> </p>
		</div>

		<div class="col-sm-3">
			<p> <%= @tag[index+1]["value"] if @tag[index+1] %> </p>
		</div>

		<div class="col-sm-3">
			<p> <%= @tag[index+2]["value"] if @tag[index+2] %> </p>
		</div>

		<div class="col-sm-3">
			<p> <%= @tag[index+3]["value"] if @tag[index+3] %> </p>
		</div>

		</div>
	<% end %>  
<% end %>

<hr>
<% if @posted_question %>
	<div class="row">
		<div class="col-sm-12">
			<strong> Question : </strong>  <%= @posted_question["value"] %><br>
			<strong> Tags : </strong> <%= @posted_question["tags"] %><br>			
		</div>
	</div>
<% end %>