config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'users/new'
  get  '/signup' , to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create' 
  post 'questions',to: 'questions#create'
  get '/search',  to: 'questions#new' 
  post '/search',  to: 'questions#search'
  get '/logout', to: 'sessions#destroy'
  post '/post_answer', to: 'answers#create'
  post '/post_comment', to: 'comments#create'
  post '/post_vote', to: 'votes#create'
  get '/show_question', to: 'questions#index'
  get '/show_user', to: 'users#index'
  get '/show_answer', to: 'answers#index'
  get '/delete_question', to: 'questions#destroy'
  get '/delete_answer', to: 'answers#destroy'
  post '/post_tags', to: 'tags#create'
  get '/show_comment', to: 'comments#index'
  get 'delete_comment', to: 'comments#destroy'
  # get '/questions', to: 'questions#show'
  # patch 'questions/:id', to: 'questions#update'
  post '/edit_question', to: 'questions#update'
  get '/edit_question', to: 'questions#edit'

  post '/edit_answer', to: 'answers#update'
  get '/edit_answer', to: 'answers#edit'

  post '/edit_comment', to: 'comments#update'
  get '/edit_comment', to: 'comments#edit'


end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Bringing <a href="https://www.1mg.com/"> Back</a>
    The <a href="https://www.1mg.com/">Healthcare</a>
  </small>
  <nav>
    <ul>
      <li><a href="https://www.1mg.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "stack overflow front", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path  %></li>
        <% if logged_in? %> 
					<li> <%= link_to "User Info", show_user_path %></li>
					<li> <%= link_to "Search", search_path %> </li>
					<li> <%= link_to "Log out", logout_path , method: :delete %></li>
        <% else %>
					<li><%= link_to "Log In", login_path %></li>
				<% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_tag '', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="mainBody">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      <%= params if Rails.env.development? %>
    </div>
  </body>
</html>